apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cs-template
  janus-idp.io/tekton: cs-template
  backstage.io/kubernetes-id: cs-template
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cs-template
resources:
- deployment.yaml
- route.yaml
- service.yaml
